### ISSUE TITLE
Add pre-commit hook in package.json

### ISSUE THREAD

**Issue by mazipan** [mazipan/awesome-sde-id-medium#7]
Now we have job for generate json file that we can run with `node READMEtoJSON`, please put this in pre-commit hook so all people will run this task before committing changes.

You can see this package https://www.npmjs.com/package/pre-commit
For implement this.
This issue is dependent with #6 because we have no `package.json` yet.

**Comment by mazipan** [comment]
#6 already merged

**Comment by RanadeepPolavarapu** [comment]
@mazipan PR is up for this. #10 .
